language: node_js

node_js:
  - stable
services:
  - postgresql

install:
  - npm install
before_script:
  - psql -c 'drop database if exists more-recipes-test;' -U postgres
  - psql -c 'create database more-recipes-test;' -U postgres

script:
  - npm test


after_success: npm run coveralls