const LOGIN = 'LOGIN';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
<<<<<<< HEAD
const SIGNUP = 'SIGNUP';
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
const LOGOUT = 'LOGOUT';
=======
>>>>>>> cb2e109c8349566d1ac2dee7dcd5874302d9c13e

export {
  LOGIN,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
<<<<<<< HEAD
  SIGNUP,
  SIGNUP_SUCCESS,
  SIGNUP_FAILURE,
  LOGOUT
=======
>>>>>>> cb2e109c8349566d1ac2dee7dcd5874302d9c13e
};
