const GET_RECIPES = 'GET_RECIPES';
const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
const GET_RECIPES_FAILURE = 'GET_RECIPES_FAILURE';
const VIEW_RECIPE = 'VIEW_RECIPE';
const VIEW_RECIPE_SUCCESS = 'VIEW_RECIPE_SUCCESS';
const VIEW_RECIPE_FAILURE = 'VIEW_RECIPE_FAILURE';
const ADD_RECIPE = 'ADD_RECIPE';
const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS';
const ADD_RECIPE_FAILURE = 'ADD_RECIPE_FAILURE';
const DELETE_RECIPE = 'DELETE_RECIPE';
const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
const DELETE_RECIPE_FAILURE = 'DELETE_RECIPE_FAILURE';
const UPDATE_RECIPE = 'UPDATE_RECIPE';
const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';
const UPDATE_RECIPE_FAILURE = 'UPDATE_RECIPE_FAILURE';
const FAVORITE_RECIPE = 'FAVORITE_RECIPE';
const FAVORITE_RECIPE_SUCCESS = 'FAVORITE_RECIPE_SUCCESS';
const FAVORITE_RECIPE_FAILURE = 'FAVORITE_RECIPE_FAILURE';
const RETRIEVE_FAVORITE_RECIPES = 'RETRIEVE_FAVORITE_RECIPES';
const RETRIEVE_FAVORITE_RECIPES_SUCCESS = 'RETRIEVE_FAVORITE_RECIPES_SUCCESS';
const RETRIEVE_FAVORITE_RECIPES_FAILURE = 'RETRIEVE_FAVORITE_RECIPES_FAILURE';
const VIEW_RECIPE_NO_USER_ID = 'VIEW_RECIPE_NO_USER_ID';
export {
  GET_RECIPES,
  GET_RECIPES_SUCCESS,
  GET_RECIPES_FAILURE,
  VIEW_RECIPE,
  VIEW_RECIPE_NO_USER_ID,
  VIEW_RECIPE_SUCCESS,
  VIEW_RECIPE_FAILURE,
  ADD_RECIPE,
  ADD_RECIPE_SUCCESS,
  ADD_RECIPE_FAILURE,
  DELETE_RECIPE,
  DELETE_RECIPE_SUCCESS,
  DELETE_RECIPE_FAILURE,
  UPDATE_RECIPE,
  UPDATE_RECIPE_SUCCESS,
  UPDATE_RECIPE_FAILURE,
  FAVORITE_RECIPE,
  FAVORITE_RECIPE_SUCCESS,
  FAVORITE_RECIPE_FAILURE,
  RETRIEVE_FAVORITE_RECIPES,
  RETRIEVE_FAVORITE_RECIPES_SUCCESS,
  RETRIEVE_FAVORITE_RECIPES_FAILURE
};
