const GET_RECIPES = 'GET_RECIPES';
const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
const GET_RECIPES_FAILURE = 'GET_RECIPES_FAILURE';
const VIEW_RECIPE = 'VIEW_RECIPE';
const ADD_RECIPE = 'ADD_RECIPE';
const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS';
const ADD_RECIPE_FAILURE = 'ADD_RECIPE_FAILURE';

export {
  GET_RECIPES,
  GET_RECIPES_SUCCESS,
  GET_RECIPES_FAILURE,
  VIEW_RECIPE,
  ADD_RECIPE,
  ADD_RECIPE_SUCCESS,
  ADD_RECIPE_FAILURE
};
