const GET_RECIPES = 'GET_RECIPES';
const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
const GET_RECIPES_FAILURE = 'GET_RECIPES_FAILURE';

export {
  GET_RECIPES,
  GET_RECIPES_SUCCESS,
  GET_RECIPES_FAILURE
};
